# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heatingcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heatingcontrol.Sensor')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='log',
            name='device',
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['name', 'value']},
        ),
        #migrations.RemoveField(
        #    model_name='config',
        #    name='config_type',
        #),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set([('name', 'value')]),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
