# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatingcontrol', '0002_auto_20160327_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='config_type',
        ),
        migrations.AddField(
            model_name='sensor',
            name='w1_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
